# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{numeric_array}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Evan Sagge"]
  s.date = %q{2010-08-25}
  s.description = %q{Support for Array#sum, Array#mean, Array#variance, Array#standard_deviation. An ArgumentError is raised when at least one array element is non-numeric.}
  s.email = %q{evansagge@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/numeric_array.rb",
     "spec/numeric_array_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/evansagge/numeric_array}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extension methods for manipulating and calculating an array of numbers}
  s.test_files = [
    "spec/numeric_array_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
  end
end

